// <auto-generated />
namespace Sell_Train_Ticket.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddDepartureTimeAndArrivalTimeToTrip : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddDepartureTimeAndArrivalTimeToTrip));
        
        string IMigrationMetadata.Id
        {
            get { return "202206021217566_AddDepartureTimeAndArrivalTimeToTrip"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
